### ISSUE TITLE
All vertices are detected as boundary vertices

### ISSUE THREAD

**Issue by EmJay276** [sgsellan/gpytoolbox#68] opened 2023-02-27 09:17 UTC
I tried to remesh some models from the [Engineering Shape Benchmark (ESB)](https://engineering.purdue.edu/cdesign/wp/downloads/)

For example `backdoor.stl` from the [Flat-Thin Wallcomponents.tar.gz](https://engineering.purdue.edu/cdesign/wp/wp-content/uploads/2012/10/Flat-Thin-Wallcomponents.tar.gz) 

The result using `remesh_botsch` is exactly the same as the input.
```
import gpytoolbox as gpy
v, f = gpy.read_mesh(r"C:\Users\Michael\Desktop\Flat-Thin-Wallcomponents\Flat-Thin Wallcomponents\Back Doors\backdoor.stl")
u, g = gpy.remesh_botsch(v, f, h=None)
```

I discovered all vertices of the model are detected as boundary vertices by `boundary_vertices(f)`

But the model has clearly some "inner" vertices (at least on the rounded part in the middle.
![grafik](https://user-images.githubusercontent.com/8619525/221522984-2d544e55-51a0-44ea-9346-a3ad6605f50e.png)

**Comment by EmJay276** [comment] 2023-02-27 09:40
I've added a PR https://github.com/sgsellan/gpytoolbox/pull/69 with a warning in the case of all vertices are boundary vertices.

But I think there is an issue with the `boundary_vertices` method in this case.

**Comment by EmJay276** [comment] 2023-02-27 12:18
I noticed a really weird behaviour, the stl seems to have unique vertices per face (=> the faces are unconnected)
I don't know if this is due to the file or due to the new STL import.

**Comment by sgsellan** [comment] 2023-02-27 16:17
Hi @EmJay276 ! Thanks for submitting this issue. 

In fact, this is the intended behaviour: an STL file contains no connectivity information, as it just stores a set of individual triangles without any relations between them. So, reading an STL file will return a lot of individual triangles and, since there's no connection between them, boundary_faces will correctly identify all of them as boundaries.

Still, I can see why this is confusing. The easiest thing to do is add a well-documented flag to the stl reader that optionally merges all duplicate vertices (with `remove_duplicate_vertices`). I believe the boundary will be properly identified in that case.

**Comment by sgsellan** [comment] 2023-02-27 16:39
I just pushed an enhancement of our STL `read_mesh` function to automatically merge STL vertices by default (pushed to. main instead of a PR branch because I haven't had enough caffeine today, it seems haha). Can you confirm this issue is solved and if so, close it?

Thanks for reporting!

**Comment by EmJay276** [comment] 2023-02-27 19:15
Thanks for the fast fix! You should get some coffee ☕ 😄 
Yes, I think the default behaviour should be to merge duplicate vertices when importing an STL.

**Closed** 2023-02-27 19:16 UTC
Labels: enhancement
